"""empty message

Revision ID: adb5041f5eb7
Revises: 
Create Date: 2022-07-21 15:30:01.909038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb5041f5eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ar_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_user_user_name'), 'ar_user', ['user_name'], unique=False)
    op.create_table('ar_geo_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bid', sa.String(length=20), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('state', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['ar_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_geo_history_bid'), 'ar_geo_history', ['bid'], unique=False)
    op.create_index(op.f('ix_ar_geo_history_name'), 'ar_geo_history', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ar_geo_history_name'), table_name='ar_geo_history')
    op.drop_index(op.f('ix_ar_geo_history_bid'), table_name='ar_geo_history')
    op.drop_table('ar_geo_history')
    op.drop_index(op.f('ix_ar_user_user_name'), table_name='ar_user')
    op.drop_table('ar_user')
    # ### end Alembic commands ###
